require('packer-plugins')
require('cmp')
require('lsp')
vim.api.nvim_set_keymap('i', 'kj', '<Esc>', {})
vim.api.nvim_set_keymap('i', 'jk', '<ESC>', {})
vim.api.nvim_set_keymap('n', 'ff', ':Telescope find_files <CR>', {})
vim.api.nvim_set_keymap('n', 'ft', ':Vex 25 <CR>', {})
vim.api.nvim_set_keymap('n', 'git', ':LazyGit <CR>', {})
vim.api.nvim_set_keymap('n', 'grep', ':Telescope live_grep<CR>', {})
vim.api.nvim_set_keymap('n', 'gs', ':Telescope grep_string<CR>', {})
